### PR TITLE
Remove dependency on 'ttfmake-customizer-chosen'

### PR DESCRIPTION
**Pull request by JJJ**
We are looking into incorporating the [WP Chosen](https://github.com/stuttter/wp-chosen) plugin into the Customizer, and identified an incompatibility with Make theme.

WP Chosen would want to deregister the `ttfmake-customizer-chosen` scripts & styles, but because they are listed as dependencies in Make theme, they are automatically slurped back in by WordPress's dependency manager.

Removing these dependencies doesn't appear to break anything, and at a cursory glance the Make theme customizer sections appear visually indifferent without the dependency.

### CODE REVIEW

**Comment by johnjamesjacoby** [comment]
before
after

**Comment by johnjamesjacoby** [comment]
In a perfect world, Chosen would be included in WordPress core and the Make them wouldn't need to include it and WP Chosen wouldn't need to exist.

Including Chosen in a plugin or theme is akin to including jQuery all those years ago. It's impossible not to have multiple versions enqueued if multiple plugins or themes need to use it. For example, Easy Digital Downloads and CMB2 also bundle Chosen, and any styling tweaks will bleed over into each others implementations.

Making the bundled libraries as easy as possible to unplug is about all that can be done if it's a true dependency for customizer controls in Make theme.

**Comment by coreymckrill** [comment]
Hi @johnjamesjacoby, thanks for the PR! We'd love to see Chosen included in core, and are happy to work with you to make sure everything is compatible. With that in mind, I have a counter proposal for you:

We recently changed the way we register several third party script/style libraries so that they are no longer prefixed with `ttfmake`, on the notion that it would help to reduce the number of duplicate libraries loading on a page. Somehow, though, Chosen was overlooked for this. So here's my proposal:

* Instead of having to maintain a special function for Make in your plugin, let's change the style and script handles in Make to just `chosen`, the same that the plugin uses. This way, the theme won't register the library if the plugin already has. Then, eventually, after Chosen gets into core, we won't have to register it at all, as long as we make sure our implementation of Chosen is compatible with the version of the script in core.
* For compatibility with older versions of Make that still use the old handle and dependencies, I believe there's a way to modify a registered style/script's dependency array. I can submit a PR to your plugin if you're interested.
* We only use the `master` branch of the Make repo for the version of the code that is available in the WP.org theme directory. Could you submit a new PR to the `develop` branch?

Thanks again. Let me know what you think.

**Comment by johnjamesjacoby** [comment]
Hey @coreymckrill!

That is also a great solution, and I think the preferable one given that you're comfortable removing the namespace. I may not get to this until Thursday, but I'll resubmit another PR then if no one's beat me to it.

Thanks!

**Comment by JJJ** [comment]
The client I was working with is no longer, and I haven't made any progress, so I'm closing this to get it out of the queue.

**Pull request closed without merging**
